version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: eshop
      POSTGRES_USER: eshop_user
      POSTGRES_PASSWORD: eshop_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  postgres_data: